package com.semantive.geoys.model.entity

import com.semantive.geoys.dunno.pgSlickDriver.simple._

/**
 * @author Amadeusz Kosik <akosik@semantive.com>
 */
abstract class BasicFeatureTable[T] (tableName: String) extends Table[T](tableName) {
  /** Id generated by the db */
  def id          = column[Int]("id", O.PrimaryKey, O.AutoInc)
  /** Name of the country. */
  def name        = column[String]("name", O.DBType("VARCHAR(200)"))
  /** Name of the country (ASCII characters only). */
  def asciiName   = column[String]("ascii_name", O.DBType("VARCHAR(200)"))
  /** Id of the country in the Geonames db. */
  def geoId       = column[Int]("geo_id")

  /** UNIQUE index on geoId. */
  def idxGeoId    = index("uq_" + tableName +  "_geo_id", geoId, unique = true)
}
